baseURL = 'https://landonbjackson.dev/'

# Theme Name
theme = 'hugo-bearblog'

# Basic metadata configuration.
title = "Landon's Blog"
author = "Landon Jackson"
copyright = "Copyright © 2020, Landon Jackson."

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[permalinks]
  blog  = "/blog/:slug/"
  posts = "/posts/:slug/"
  music = "/music/:slug/"
  projects = "/projects/:slug/"
  home = "/home/:slug/"

[params]
    favicon = "images/favicon.png"
    images = ["images/share.png"]

# Allows me to use HTML in Markdown WOAH!!!!
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
